--
cook:
  special: cook78-config
---
spring:
  config:
    activate:
      on-profile: development
  
cook:
  special: cook100-development
---
spring:
  config:
    activate:
      on-profile: encypt
  
cook:
  special: cook100-encrytion
